### ISSUE TITLE
Bot does not respond in group chats

### ISSUE THREAD

**Issue by TimurKiyivinski** [hangyas/TelegramBot#12]
I get the following error when adding and executing commands from a group chat:
```
update was not handled because: Error 400 in call to Telegram API: {"ok":false,"error_code":400,"description":"Bad Request: chat not found"}
```
However, the bot seems able operate normally when chatting with it directly.
Apart from doing exactly as done in the example and registering the Bot with the BotFather, is there anything else required to get a bot working in a group chat?

**Comment by hangyas** [comment]
That should be enough. What does your command do? I would guess you are calling `send_message` with a username, for group chats it has to be `send_message msg.chat.id`

**Comment by TimurKiyivinski** [comment]
I'm fairly new to Crystal, so you'll have to guide me a bit because I'm not quite clear what you mean. My code is pretty similar to the example:
```crystal
def initialize(@token)
    super("...", @token)

    cmd "example" do |msg, params|
        # process here
        reply msg, some_reply_string
    end
end
```
Replacing `reply msg, some_reply_string` with `send_message msg.chat.id, some_reply_string`  does not seem to make a difference for me.

**Comment by hangyas** [comment]
Hm, both versions work for me. BotFather has /setjoingroups command, but I don't know how does that work though.

**Comment by TimurKiyivinski** [comment]
Odd, I have `/setjoingroups` set to `Enabled`. The code for the testing bot I'm writing is available [here](https://github.com/TimurKiyivinski/san_your_not_youre_bot) if you want to see what I might be doing wrong.

**Comment by hangyas** [comment]
Ok, I had similar problem, removing and readding the bot fixed it. I have no idea what's going on but looks like the problem is on Telegrams side.

**Comment by TimurKiyivinski** [comment]
Removing and re-adding does not seem to work for me. However, renaming the command seemed to have worked on one chat but not all. This seems related: https://stackoverflow.com/questions/40560576/telegram-bot-doesnt-work-on-certain-groups

Whatever the case, as this is a Telegram issue, I'll close the issue. Thanks for the help!
